version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-node-app
    container_name: node-app
    volumes:
      - ./:/app           # Монтируем исходный код
      - node_modules:/app/node_modules  # Том для кэширования node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

volumes:
  node_modules:  # Именованный том для node_modules